### ISSUE TITLE
Question: Path-to-hive and Path-to-flower it's not showing

### ISSUE THREAD

**Issue by comonier** [AlonsoAliaga/BetterBees#12]
Hello, Path-to-hive and Path-to-flower it's not showing
   What should i do to enable it ?

```yaml
  Bees:
    Path-to-hive:
      #If enabled, it will show a line between bee and his hive location if available.
      Enabled: true
      #Color for particles to hive. Color must be in Hex format. Do NOT include the #
      #You can use this https://www.google.com/search?q=color+pick
      Color: "ebdc13"
      #Time in seconds the path to hive will be displayed. Default 2
      Time: 10
    Path-to-flower:
      #If enabled, it will show a line between bee and his flower location if available.
      Enabled: true
      #Color for particles to flower. Color must be in Hex format. Do NOT include the #
      #You can use this https://www.google.com/search?q=color+pick
      Color: "eb2113"
      #Time in seconds the path to flower will be displayed. Default 2
      Time: 10
```
      
My Particles are all enabled
![image](https://user-images.githubusercontent.com/19571541/220630773-69a4960e-fe90-4cf3-bfdc-9ffd08efb80e.png)

But there are no particles being shown between the bees and the hive
![image](https://user-images.githubusercontent.com/19571541/220630868-4dc42e96-24c7-41ae-ac84-6529236eb70f.png)
